name: convergent-evo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - mafft>=7.5
  - clustalo>=1.2
  - trimal>=1.5
  - fasttree>=2.1
  - iqtree>=2.2
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - biopython>=1.81
  - jupyter>=1.0
  - ete3>=3.1
  - pip:
    - ete4>=4.4
    - pymsaviz>=0.5
